[tool.poetry]
name = "cruft"
version = "1.1.3"
description = "Allows you to maintain all the necessary cruft for packaging and building projects separate from the code you intentionally write. Built on-top of CookieCutter."
authors = ["Timothy Crosley <timothy.crosley@gmail.com>"]
license = "MIT"
readme = "README.md"
include = ["cruft/binaries/patch-2.7.6-macos"]

[tool.poetry.dependencies]
python = "^3.6"
cookiecutter = "^1.6"
gitpython = "^3.0"
hug = "^2.6"
examples = "^1.0"
toml = { version = "^0.10", optional = true }

[tool.poetry.extras]
pyproject = ["toml"]

[tool.poetry.dev-dependencies]
vulture = "^1.0"
bandit = "^1.6"
safety = "^1.8"
isort = "^4.3"
flake8-bugbear = "^19.8"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
mypy = "^0.730.0"
ipython = "^7.7"
pytest = "^5.0"
pytest-cov = "^2.7"
pytest-mock = "^1.10"
pep8-naming = "^0.8.2"
portray = "^1.3.0"
hypothesis-auto = "^1.1"

[tool.poetry.scripts]
cruft = "cruft.cli:__hug__.cli"

[tool.portray.mkdocs.theme]
favicon = "art/logo.png"
logo = "art/logo.png"
name = "material"
palette = {primary = "orange", accent = "cyan"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.cruft]
skip = ["cruft/__init__.py", "tests"]
